### ISSUE TITLE
Go output has spaces in const variables

### ISSUE THREAD

**Issue by andyedison** [glideapps/quicktype#1205] opened 2019-04-12 18:26 UTC
Greetings!

First off, awesome little app! It's super cool!

I did notice when playing around with the example pokedex.json, the go output has spaces in the const variables

```go
type Type string
const (
	Bug Type = "Bug"
	Dark Type = "Dark"
	Dragon Type = "Dragon"
	Electric Type = "Electric"
	Fairy Type = "Fairy"
	Fighting Type = "Fighting"
	Fire Type = "Fire"
	Flying Type = "Flying"
	Ghost Type = "Ghost"
	Grass Type = "Grass"
	Ground Type = "Ground"
	Ice Type = "Ice"
	Normal Type = "Normal"
	Poison Type = "Poison"
	Psychic Type = "Psychic"
	Rock Type = "Rock"
	Steel Type = "Steel"
	Water Type = "Water"
)
```

**Comment by inferrinizzard** [comment] 2024-05-27 01:15
Closing this as a non issue, this works as intended for Go enums

**Closed by inferrinizzard** 2024-05-27 01:15 UTC
